# Generated by Django 3.2.25 on 2025-07-07 11:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_claims'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.item_image_file_path),
        ),
    ]
